version: "3.8"

services:
  apache-nifi: 
    container_name: apache-nifi
    build: ./apache_nifi-service
    user: root
    ports:
      - 8443:8443
      - 7001:7001
    volumes:
      - ./nifi-volume/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi-volume/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi-volume/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi-volume/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi-volume/state:/opt/nifi/nifi-current/state
      - ./nifi-volume/logs:/opt/nifi/nifi-current/logs
      - ./nifi-volume/conf:/opt/nifi/nifi-current/conf
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB

  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    depends_on:
      - db

  prisma-migrate:
    container_name: prisma-migrate
    build: ./prisma-service
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_URL=postgres://postgres:postgres@db:5432/postgres?connect_timeout=300
    depends_on:
      - db

  nifi-registry:
    container_name: nifi-registry
    user: root
    image: apache/nifi-registry
    ports:
      - 18080:18080
    environment:
      - LOG_LEVEL=INFO
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
      - ./nifi_registry-volume/database:/opt/nifi-registry/nifi-registry-current/database:rw
      - ./nifi_registry-volume/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage:rw

