version: "3.8"

services:
  apache-nifi: 
    container_name: apache-nifi
    build: ./apache-nifi-service
    ports:
      - 8443:8443
      - 7001:7001
    volumes:
      - apache-nifi-volume:/opt/nifi/nifi-current/
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB

  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    depends_on:
      - db

  prisma-migrate:
    container_name: prisma-migrate
    build: ./prisma-service
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_URL=postgres://postgres:postgres@db:5432/postgres?connect_timeout=300
    depends_on:
      - db

volumes:
  postgres-volume:
  apache-nifi-volume:
